### PR TITLE
tickshift move enable

### PR DESCRIPTION
**Pull request by HausemasterIssue**
cool feature that i like in tickshift. also u could add movement checks idfk.

p.s. why do you use this. everywhere in your code? i don't like it, its kinda just bloat to me idk

### CODE REVIEW

**Comment by Sxmurai** [comment]
It's not bloat? It's a feature in it. Use it if you're making a pull
request use it. It's a code style not bloat. Plus I've been used to
JavaScript for 2ish years so

**Comment by linustouchtips** [comment]
this. pointer is only necessary if you have multiple things of the same name, so technically it is bloat and makes the client look like compiler code lol. but at least the code is clean :P

**Comment by HausemasterIssue** [comment]
^

**Comment by Sxmurai** [comment]
I still like it, and it's how most of the code is written regardless. So id
atleast like to keep it clean

**Pull request closed without merging**
