### PR TITLE
switch back legit

### PR DESCRIPTION
**Pull request by HausemasterIssue**

### CODE REVIEW

**Comment by HausemasterIssue** [comment]
what?

**Comment by Sxmurai** [comment]
wouldn't even work, the issue wasn't even with switching back.

**Comment by Sxmurai** [comment]
plus incorrect use of the switchTo method, therefore would cause an error

**Comment by HausemasterIssue** [comment]
ok, it's just for some reason eclipse just forgets it's forge every time i import the project so i gotta guess lmao

**Comment by Sxmurai** [comment]
this is why i use intellij, intellij on tope

**Pull request closed without merging**
