### PR TITLE
rubberband mode

### PR DESCRIPTION
**Pull request by HausemasterIssue**
it works lol. i might or you can add something where if a crystal can pop you or kill you, it will disable. or if you take more than a specified amount of damage it will disable. this is to prevent you from getting fucked up like this guy https://www.youtube.com/watch?v=8_Veg0ZSs-U 

the code works accept pr pls

### CODE REVIEW

**Comment by HausemasterIssue** [comment]
pr is 💀

**Comment by Sxmurai** [comment]
and which client did you get this from?

**Comment by HausemasterIssue** [comment]
uh, i got inspiration from momentum :(

**Comment by HausemasterIssue** [comment]
you don't have to accept lol

**Comment by Sxmurai** [comment]
just making sure cause im trying to remove skidded shit, ill probably end up figuring out another way to rubberband you with my own code. it shouldnt be too hard

**Pull request closed without merging**
