### PR TITLE
tick delays should be floats

### PR DESCRIPTION
**Pull request by HausemasterIssue**
u need decimal precision, cuz sometimes u will do 2.5 ticks or smthin like that

### CODE REVIEW

**Comment by Sxmurai** [comment]
how the fuck are you supposed to calculate half ticks, at that point youd just be calculating the milliseconds and what fucking client does that

**Comment by Sxmurai** [comment]
cause the event only fires every 1 tick, not a half tick or shit like that

**Comment by Sxmurai** [comment]
and if i were to do that, id have to use milliseconds to calculate a half tick (which is ~25ms iirc) which is what i was using for delays before, so a tick delay would be useless at that point

**Comment by HausemasterIssue** [comment]
ok whole integers works ig, i didnt know half ticks didnt work lol

**Pull request closed without merging**
