### PR TITLE
autorespawn

### PR DESCRIPTION
**Pull request by HausemasterIssue**
useful if you antiafk at 2b spawn and some retard kills you

### CODE REVIEW

**Comment by Sxmurai** [comment]
i was probably gonna add more onto this, eg death coords saved, etc

**Comment by HausemasterIssue** [comment]
ok, but accept it for now, we can always modify it later.

**Comment by Sxmurai** [comment]
well its using the wrong event (the event name is UpdateEvent and i use it in every other module, which automatically checks if it can access the world and player without a NPE)

**Comment by HausemasterIssue** [comment]
ight, let's fix it tommorow

**Pull request closed without merging**
